/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./.vitepress/theme/components/404.vue')['default']
    ArticleMetadata: typeof import('./.vitepress/theme/components/ArticleMetadata.vue')['default']
    BackToTop: typeof import('./.vitepress/theme/components/BackToTop.vue')['default']
    Comment: typeof import('./.vitepress/theme/components/comment.vue')['default']
    Confetti: typeof import('./.vitepress/theme/components/confetti.vue')['default']
    HomeUnderline: typeof import('./.vitepress/theme/components/HomeUnderline.vue')['default']
    MAsideSponsors: typeof import('./.vitepress/theme/components/MAsideSponsors.vue')['default']
    MNavLink: typeof import('./.vitepress/theme/components/MNavLink.vue')['default']
    MNavLinks: typeof import('./.vitepress/theme/components/MNavLinks.vue')['default']
    MyLayout: typeof import('./.vitepress/theme/components/MyLayout.vue')['default']
    PostCopyright: typeof import('./.vitepress/theme/components/postCopyright.vue')['default']
    Tag: typeof import('./.vitepress/theme/components/tag.vue')['default']
    WordCloud: typeof import('./.vitepress/theme/components/wordCloud.vue')['default']
  }
}
